### ISSUE TITLE
UI dropdowns don't close when clicked

### ISSUE THREAD

**Issue by theJohnnyBrown** [plotly/react-pivottable#8]
For example when changing the renderer or aggregator, they don't close until they are clicked twice. This behavior is present in the demo, is it intentional?

**Comment by nicolaskruchten** [comment]
Yes, this is intentional :)

The idea was to let users quickly try different visualizations before settling on one. There are actually three ways of closing the dropdown: clicking on the close box in the top-right, clicking elsewhere in on the component, or clicking on the selection again.

I'm not wedded to this style of interaction, and if it's too confusing or if there are better alternatives I'm open to exploring them! Perhaps an explicit "preview" button on hover?
